apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 172.16.2.10/test/helloworld:0.0.1
        livenessProbe: 
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        ports:
        - containerPort: 8000

